/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedApplicationsRouteImport } from './routes/_authenticated/applications'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedImportRouteImport } from './routes/_authenticated/import'
import { Route as AuthenticatedMasterResumeRouteImport } from './routes/_authenticated/master-resume'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedJobsIndexRouteImport } from './routes/_authenticated/jobs.index'
import { Route as AuthenticatedJobsJobIdIndexRouteImport } from './routes/_authenticated/jobs.$jobId.index'
import { Route as AuthenticatedJobsJobIdApplyRouteImport } from './routes/_authenticated/jobs.$jobId.apply'
import { Route as AuthenticatedJobsJobIdAtsRouteImport } from './routes/_authenticated/jobs.$jobId.ats'
import { Route as AuthenticatedJobsJobIdCoverLetterRouteImport } from './routes/_authenticated/jobs.$jobId.cover-letter'
import { Route as AuthenticatedJobsJobIdMatchRouteImport } from './routes/_authenticated/jobs.$jobId.match'
import { Route as AuthenticatedJobsJobIdPreviewRouteImport } from './routes/_authenticated/jobs.$jobId.preview'
import { Route as AuthenticatedJobsJobIdTailoredRouteImport } from './routes/_authenticated/jobs.$jobId.tailored'
import { Route as AuthenticatedJobsJobIdVersionsRouteImport } from './routes/_authenticated/jobs.$jobId.versions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedApplicationsRoute =
  AuthenticatedApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImportRoute = AuthenticatedImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMasterResumeRoute =
  AuthenticatedMasterResumeRouteImport.update({
    id: '/master-resume',
    path: '/master-resume',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJobsIndexRoute = AuthenticatedJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJobsJobIdIndexRoute =
  AuthenticatedJobsJobIdIndexRouteImport.update({
    id: '/jobs/$jobId/',
    path: '/jobs/$jobId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedJobsJobIdApplyRoute =
  AuthenticatedJobsJobIdApplyRouteImport.update({
    id: '/jobs/$jobId/apply',
    path: '/jobs/$jobId/apply',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedJobsJobIdAtsRoute =
  AuthenticatedJobsJobIdAtsRouteImport.update({
    id: '/jobs/$jobId/ats',
    path: '/jobs/$jobId/ats',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedJobsJobIdCoverLetterRoute =
  AuthenticatedJobsJobIdCoverLetterRouteImport.update({
    id: '/jobs/$jobId/cover-letter',
    path: '/jobs/$jobId/cover-letter',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedJobsJobIdMatchRoute =
  AuthenticatedJobsJobIdMatchRouteImport.update({
    id: '/jobs/$jobId/match',
    path: '/jobs/$jobId/match',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedJobsJobIdPreviewRoute =
  AuthenticatedJobsJobIdPreviewRouteImport.update({
    id: '/jobs/$jobId/preview',
    path: '/jobs/$jobId/preview',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedJobsJobIdTailoredRoute =
  AuthenticatedJobsJobIdTailoredRouteImport.update({
    id: '/jobs/$jobId/tailored',
    path: '/jobs/$jobId/tailored',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedJobsJobIdVersionsRoute =
  AuthenticatedJobsJobIdVersionsRouteImport.update({
    id: '/jobs/$jobId/versions',
    path: '/jobs/$jobId/versions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/applications': typeof AuthenticatedApplicationsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/import': typeof AuthenticatedImportRoute
  '/master-resume': typeof AuthenticatedMasterResumeRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/jobs/': typeof AuthenticatedJobsIndexRoute
  '/jobs/$jobId/apply': typeof AuthenticatedJobsJobIdApplyRoute
  '/jobs/$jobId/ats': typeof AuthenticatedJobsJobIdAtsRoute
  '/jobs/$jobId/cover-letter': typeof AuthenticatedJobsJobIdCoverLetterRoute
  '/jobs/$jobId/match': typeof AuthenticatedJobsJobIdMatchRoute
  '/jobs/$jobId/preview': typeof AuthenticatedJobsJobIdPreviewRoute
  '/jobs/$jobId/tailored': typeof AuthenticatedJobsJobIdTailoredRoute
  '/jobs/$jobId/versions': typeof AuthenticatedJobsJobIdVersionsRoute
  '/jobs/$jobId/': typeof AuthenticatedJobsJobIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/applications': typeof AuthenticatedApplicationsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/import': typeof AuthenticatedImportRoute
  '/master-resume': typeof AuthenticatedMasterResumeRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/jobs': typeof AuthenticatedJobsIndexRoute
  '/jobs/$jobId/apply': typeof AuthenticatedJobsJobIdApplyRoute
  '/jobs/$jobId/ats': typeof AuthenticatedJobsJobIdAtsRoute
  '/jobs/$jobId/cover-letter': typeof AuthenticatedJobsJobIdCoverLetterRoute
  '/jobs/$jobId/match': typeof AuthenticatedJobsJobIdMatchRoute
  '/jobs/$jobId/preview': typeof AuthenticatedJobsJobIdPreviewRoute
  '/jobs/$jobId/tailored': typeof AuthenticatedJobsJobIdTailoredRoute
  '/jobs/$jobId/versions': typeof AuthenticatedJobsJobIdVersionsRoute
  '/jobs/$jobId': typeof AuthenticatedJobsJobIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/applications': typeof AuthenticatedApplicationsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/import': typeof AuthenticatedImportRoute
  '/_authenticated/master-resume': typeof AuthenticatedMasterResumeRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/jobs/': typeof AuthenticatedJobsIndexRoute
  '/_authenticated/jobs/$jobId/apply': typeof AuthenticatedJobsJobIdApplyRoute
  '/_authenticated/jobs/$jobId/ats': typeof AuthenticatedJobsJobIdAtsRoute
  '/_authenticated/jobs/$jobId/cover-letter': typeof AuthenticatedJobsJobIdCoverLetterRoute
  '/_authenticated/jobs/$jobId/match': typeof AuthenticatedJobsJobIdMatchRoute
  '/_authenticated/jobs/$jobId/preview': typeof AuthenticatedJobsJobIdPreviewRoute
  '/_authenticated/jobs/$jobId/tailored': typeof AuthenticatedJobsJobIdTailoredRoute
  '/_authenticated/jobs/$jobId/versions': typeof AuthenticatedJobsJobIdVersionsRoute
  '/_authenticated/jobs/$jobId/': typeof AuthenticatedJobsJobIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/applications'
    | '/dashboard'
    | '/import'
    | '/master-resume'
    | '/profile'
    | '/jobs/'
    | '/jobs/$jobId/apply'
    | '/jobs/$jobId/ats'
    | '/jobs/$jobId/cover-letter'
    | '/jobs/$jobId/match'
    | '/jobs/$jobId/preview'
    | '/jobs/$jobId/tailored'
    | '/jobs/$jobId/versions'
    | '/jobs/$jobId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/applications'
    | '/dashboard'
    | '/import'
    | '/master-resume'
    | '/profile'
    | '/jobs'
    | '/jobs/$jobId/apply'
    | '/jobs/$jobId/ats'
    | '/jobs/$jobId/cover-letter'
    | '/jobs/$jobId/match'
    | '/jobs/$jobId/preview'
    | '/jobs/$jobId/tailored'
    | '/jobs/$jobId/versions'
    | '/jobs/$jobId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/applications'
    | '/_authenticated/dashboard'
    | '/_authenticated/import'
    | '/_authenticated/master-resume'
    | '/_authenticated/profile'
    | '/_authenticated/jobs/'
    | '/_authenticated/jobs/$jobId/apply'
    | '/_authenticated/jobs/$jobId/ats'
    | '/_authenticated/jobs/$jobId/cover-letter'
    | '/_authenticated/jobs/$jobId/match'
    | '/_authenticated/jobs/$jobId/preview'
    | '/_authenticated/jobs/$jobId/tailored'
    | '/_authenticated/jobs/$jobId/versions'
    | '/_authenticated/jobs/$jobId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/applications': {
      id: '/_authenticated/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof AuthenticatedApplicationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/import': {
      id: '/_authenticated/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AuthenticatedImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/master-resume': {
      id: '/_authenticated/master-resume'
      path: '/master-resume'
      fullPath: '/master-resume'
      preLoaderRoute: typeof AuthenticatedMasterResumeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jobs/': {
      id: '/_authenticated/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof AuthenticatedJobsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jobs/$jobId/': {
      id: '/_authenticated/jobs/$jobId/'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId/'
      preLoaderRoute: typeof AuthenticatedJobsJobIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jobs/$jobId/apply': {
      id: '/_authenticated/jobs/$jobId/apply'
      path: '/jobs/$jobId/apply'
      fullPath: '/jobs/$jobId/apply'
      preLoaderRoute: typeof AuthenticatedJobsJobIdApplyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jobs/$jobId/ats': {
      id: '/_authenticated/jobs/$jobId/ats'
      path: '/jobs/$jobId/ats'
      fullPath: '/jobs/$jobId/ats'
      preLoaderRoute: typeof AuthenticatedJobsJobIdAtsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jobs/$jobId/cover-letter': {
      id: '/_authenticated/jobs/$jobId/cover-letter'
      path: '/jobs/$jobId/cover-letter'
      fullPath: '/jobs/$jobId/cover-letter'
      preLoaderRoute: typeof AuthenticatedJobsJobIdCoverLetterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jobs/$jobId/match': {
      id: '/_authenticated/jobs/$jobId/match'
      path: '/jobs/$jobId/match'
      fullPath: '/jobs/$jobId/match'
      preLoaderRoute: typeof AuthenticatedJobsJobIdMatchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jobs/$jobId/preview': {
      id: '/_authenticated/jobs/$jobId/preview'
      path: '/jobs/$jobId/preview'
      fullPath: '/jobs/$jobId/preview'
      preLoaderRoute: typeof AuthenticatedJobsJobIdPreviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jobs/$jobId/tailored': {
      id: '/_authenticated/jobs/$jobId/tailored'
      path: '/jobs/$jobId/tailored'
      fullPath: '/jobs/$jobId/tailored'
      preLoaderRoute: typeof AuthenticatedJobsJobIdTailoredRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jobs/$jobId/versions': {
      id: '/_authenticated/jobs/$jobId/versions'
      path: '/jobs/$jobId/versions'
      fullPath: '/jobs/$jobId/versions'
      preLoaderRoute: typeof AuthenticatedJobsJobIdVersionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedApplicationsRoute: typeof AuthenticatedApplicationsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedImportRoute: typeof AuthenticatedImportRoute
  AuthenticatedMasterResumeRoute: typeof AuthenticatedMasterResumeRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedJobsIndexRoute: typeof AuthenticatedJobsIndexRoute
  AuthenticatedJobsJobIdApplyRoute: typeof AuthenticatedJobsJobIdApplyRoute
  AuthenticatedJobsJobIdAtsRoute: typeof AuthenticatedJobsJobIdAtsRoute
  AuthenticatedJobsJobIdCoverLetterRoute: typeof AuthenticatedJobsJobIdCoverLetterRoute
  AuthenticatedJobsJobIdMatchRoute: typeof AuthenticatedJobsJobIdMatchRoute
  AuthenticatedJobsJobIdPreviewRoute: typeof AuthenticatedJobsJobIdPreviewRoute
  AuthenticatedJobsJobIdTailoredRoute: typeof AuthenticatedJobsJobIdTailoredRoute
  AuthenticatedJobsJobIdVersionsRoute: typeof AuthenticatedJobsJobIdVersionsRoute
  AuthenticatedJobsJobIdIndexRoute: typeof AuthenticatedJobsJobIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedApplicationsRoute: AuthenticatedApplicationsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedImportRoute: AuthenticatedImportRoute,
  AuthenticatedMasterResumeRoute: AuthenticatedMasterResumeRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedJobsIndexRoute: AuthenticatedJobsIndexRoute,
  AuthenticatedJobsJobIdApplyRoute: AuthenticatedJobsJobIdApplyRoute,
  AuthenticatedJobsJobIdAtsRoute: AuthenticatedJobsJobIdAtsRoute,
  AuthenticatedJobsJobIdCoverLetterRoute:
    AuthenticatedJobsJobIdCoverLetterRoute,
  AuthenticatedJobsJobIdMatchRoute: AuthenticatedJobsJobIdMatchRoute,
  AuthenticatedJobsJobIdPreviewRoute: AuthenticatedJobsJobIdPreviewRoute,
  AuthenticatedJobsJobIdTailoredRoute: AuthenticatedJobsJobIdTailoredRoute,
  AuthenticatedJobsJobIdVersionsRoute: AuthenticatedJobsJobIdVersionsRoute,
  AuthenticatedJobsJobIdIndexRoute: AuthenticatedJobsJobIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
